// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfS31zrUfk2tvDPv603wTHPMR6ZFaPEsg',
    appId: '1:958594115564:web:f63bc16d7d6629c69c42c9',
    messagingSenderId: '958594115564',
    projectId: 'hydroponic-system-61a0f',
    authDomain: 'hydroponic-system-61a0f.firebaseapp.com',
    storageBucket: 'hydroponic-system-61a0f.firebasestorage.app',
    measurementId: 'G-FDYZML7803',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS_DHuMx7T3OCDAyt7C7yX30a6KJ8XY1I',
    appId: '1:958594115564:android:f10e7d7012e11a3a9c42c9',
    messagingSenderId: '958594115564',
    projectId: 'hydroponic-system-61a0f',
    storageBucket: 'hydroponic-system-61a0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALwln3InP4t57AiU9qaFYXCUC59h2eXSY',
    appId: '1:958594115564:ios:8acc39ad809c25829c42c9',
    messagingSenderId: '958594115564',
    projectId: 'hydroponic-system-61a0f',
    storageBucket: 'hydroponic-system-61a0f.firebasestorage.app',
    iosBundleId: 'com.example.hydroponicClean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALwln3InP4t57AiU9qaFYXCUC59h2eXSY',
    appId: '1:958594115564:ios:8acc39ad809c25829c42c9',
    messagingSenderId: '958594115564',
    projectId: 'hydroponic-system-61a0f',
    storageBucket: 'hydroponic-system-61a0f.firebasestorage.app',
    iosBundleId: 'com.example.hydroponicClean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfS31zrUfk2tvDPv603wTHPMR6ZFaPEsg',
    appId: '1:958594115564:web:74ae67fdede7d71e9c42c9',
    messagingSenderId: '958594115564',
    projectId: 'hydroponic-system-61a0f',
    authDomain: 'hydroponic-system-61a0f.firebaseapp.com',
    storageBucket: 'hydroponic-system-61a0f.firebasestorage.app',
    measurementId: 'G-H0SNSP6C47',
  );
}
